### PR TITLE
update to Mori 0.3.2

### PR DESCRIPTION
**Pull request by swannodette**
Updated to Mori 0.3.2, made necessary changes for better benchmarking

### CODE REVIEW

**Comment by Pauan** [comment]
Looks good to me. Good catch on using `nth` rather than `get`. FYI, my library also uses `arguments.length` checking, so using the hardcoded-arity functions in Mori seems a bit unfair, especially because normal users won't be using them. But I'm interested to see whether it makes a big speed difference or not, so I'll accept this.

**Comment by swannodette** [comment]
@Pauan there are still other calling overheads in Mori not present in most JS libraries: a) in variadic cases, especially the factory fns like `vector`, copying arguments into an array, wrapping in an immutable data structure, & traversing the immutable data structure through polymorphic calls, b) all the critical entry points like `nth` and `get` have type checking cascade (to support arrays and strings) + custom polymorphic dispatch overheads.

**Comment by Pauan** [comment]
@swannodette That's a good point about `nth` and `get`.

By the way, what's the fastest way to create a Mori Vector from a JavaScript array? I'm currently using `mori.vector.f([1, 2, 3])` but that isn't documented, so it might not be officially supported.

**Comment by swannodette** [comment]
@Pauan in the factory function case it's probably just going to be more faster and idiomatic to do `mori.vector(1,2,3)`

**Comment by Pauan** [comment]
@swannodette Of course, but what if you already have a JavaScript array, like this:

```
var array = [...];
mori.vector.f(array);
```

Previously I was using `mori.vector.apply(null, array)`, but my intuition says that's slow.

**Comment by swannodette** [comment]
@Pauan the call may be slower but I'm pretty sure it won't matter - will be dominated by actual construction.

**Comment by Pauan** [comment]
@swannodette Okay, thanks.

**Pull request merged**
